kind: Service
apiVersion: v1
metadata:
  name: gin-k8s-auth-example
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: gin-k8s-auth-example
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gin-k8s-auth-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-k8s-auth-example
  template:
    metadata:
      labels:
        app: gin-k8s-auth-example
    spec:
      containers:
        - name: my-go
          image: quay.io/adambkaplan/gin-k8s-auth-example:latest
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
